apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: fx04vzpwi-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-bdecee23ad.2jb9.p3.openshiftapps.com/rhtap/rhtap-qe:a6f6a4107661b727e5885401fcddedc96eb96a35@sha256:202b59d9eb52a8534021eef701cabaee57e16ba2b4f732c5b6d7cd4409e0140b
          name: container-image
